import type { Food, FoodId } from "../types";

// Food is the second progression track. Flakes stay free forever so the core click
// never dries up, but everything above them is bought per pellet — which keeps the
// premium foods a decision instead of a strict upgrade.
//
// `cost` is NOT an absolute coin price: it is a multiple of the tank's current
// pellet baseline (the value of the best fish you own). Prices therefore keep pace
// with the economy at every scale, and a worm never becomes free just because you
// moved into the space aquarium.

export const FOODS: Record<FoodId, Food> = {
  flake: {
    id: "flake",
    name: "Normal Yem",
    emoji: "🟤",
    cost: 0,
    unlockCost: 0,
    tier: 0,
    valueMul: 1,
    xpMul: 1,
    comboBonus: 0,
    effect: "none",
    color: "#c98a45",
    glow: "#f0c78a",
    blurb: "Bedava. Sonsuza kadar bedava. Combo'nun yakıtı budur.",
  },
  shrimpPellet: {
    id: "shrimpPellet",
    name: "Karides Peleti",
    emoji: "🦐",
    cost: 0.9,
    unlockCost: 12000,
    tier: 1,
    valueMul: 2.4,
    xpMul: 1.5,
    comboBonus: 0,
    effect: "none",
    color: "#ff7a5c",
    glow: "#ffc6ad",
    blurb: "Değer ×2.4, büyüme ×1.5. İlk gerçek yatırım kararı.",
  },
  worm: {
    id: "worm",
    name: "Solucan",
    emoji: "🪱",
    cost: 1.0,
    unlockCost: 3e5,
    tier: 2,
    valueMul: 2.1,
    xpMul: 1.3,
    comboBonus: 1,
    effect: "split",
    color: "#e06aa0",
    glow: "#ffb3d4",
    blurb: "Suda ikiye bölünür: iki balık, iki lokma, iki combo.",
  },
  starFood: {
    id: "starFood",
    name: "Yıldız Yemi",
    emoji: "⭐",
    cost: 1.6,
    unlockCost: 6e6,
    tier: 3,
    valueMul: 3.2,
    xpMul: 2.2,
    comboBonus: 3,
    effect: "none",
    color: "#ffd93d",
    glow: "#fff3a8",
    blurb: "Her lokma combo sayacını 4 birden ilerletir. Frenzy'nin kısayolu.",
  },
  explosive: {
    id: "explosive",
    name: "Patlayıcı Yem",
    emoji: "💥",
    cost: 1.4,
    unlockCost: 1.5e8,
    tier: 4,
    valueMul: 2.6,
    xpMul: 1.6,
    comboBonus: 1,
    effect: "explode",
    color: "#ff5722",
    glow: "#ffb199",
    blurb: "Yenince 5 yem daha fırlatır. Zincirleme reaksiyonun kaynağı.",
  },
  rainbow: {
    id: "rainbow",
    name: "Gökkuşağı Peleti",
    emoji: "🌈",
    cost: 2.0,
    unlockCost: 3e9,
    tier: 5,
    valueMul: 3.6,
    xpMul: 3,
    comboBonus: 2,
    effect: "mutate",
    color: "#8ef0ff",
    glow: "#ffffff",
    blurb: "%12 ihtimalle yiyen balığı kalıcı olarak nadir varyanta çevirir (×2.5).",
  },
  mutant: {
    id: "mutant",
    name: "Mutant Yem",
    emoji: "☢️",
    cost: 3.6,
    unlockCost: 6e10,
    tier: 6,
    valueMul: 6.5,
    xpMul: 4,
    comboBonus: 3,
    effect: "enrage",
    color: "#9dff3d",
    glow: "#e2ffb0",
    blurb: "Yiyen balık çıldırır: 8 saniye boyunca ×5 hız ve ×5 üretim.",
  },
  krill: {
    id: "krill",
    name: "Altın Krill",
    emoji: "✨",
    cost: 4.5,
    unlockCost: 1.5e12,
    tier: 7,
    // The guaranteed nugget is already a ×9 on top, so the base multiplier stays low.
    valueMul: 1.2,
    xpMul: 2.5,
    comboBonus: 2,
    effect: "gold",
    color: "#ffd700",
    glow: "#fff6c2",
    blurb: "Her lokma garantili bir altın sikke bırakır. Sade ve acımasız.",
  },
};

export const FOOD_ORDER: FoodId[] = [
  "flake", "shrimpPellet", "worm", "starFood",
  "explosive", "rainbow", "mutant", "krill",
];
